name: windows

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
        toolset:
          - v141
          - v142
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout Complex Repo
        uses: actions/checkout@v2
        with:
          repository: bluequartzsoftware/complex
          path: complex
          submodules: true
      - name: Add C++ Problem Matcher
        uses: ammaraskar/msvc-problem-matcher@0.1
      - name: Setup Build Environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup NuGet Credentials
        shell: bash
        run: >
          `vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "BlueQuartzSoftware"
          -password "${{secrets.GITHUB_TOKEN}}"
      - name: Configure
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCOMPLEX_PLUGIN_SEARCH_DIRS=${{github.workspace}} -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake -DCOMPLEX_EXTRA_PLUGINS="Core;DREAM3DReview;EMMPM;Generic;ImageProcessing;ImportExport;ITKImageProcessing;OrientationAnalysis;Processing;ProgWorkshop;Reconstruction;Sampling;SimulationIO;StatsToolbox;SurfaceMeshing;SyntheticBuilding;UCSBUtilities;VolumeMeshing" -S ${{github.workspace}}/complex -B ${{github.workspace}}/build
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build
      - name: Test
        run: |
          ctest --test-dir ${{github.workspace}}/build
